### ISSUE TITLE
Add variables support

### ISSUE THREAD

**Issue by robballou** [robballou/project#1]
Add a way to define variables in project configuration:

```yaml
variables:
  foo: thing

build:
  dev:
    style: script
    # use the variable to be "thing/path"
    script: $foo/path
```
