### ISSUE TITLE
Add tests for and allow for "short" style statements

### ISSUE THREAD

**Issue by robballou** [robballou/project#2]
Often, the `project` command requires a "style" for various things (local connections, build commands, etc.) but some of these are easy to recognize via associated keys. For example:

```yaml
build:
   dev:
     style: script
     script: example.sh
```

Could be:

```yaml
build:
   dev:
     script: example.sh
```
