### ISSUE TITLE
Allow connect to piggy back off local

### ISSUE THREAD

**Issue by robballou** [robballou/project#6]
Allow `connect` environments to piggy back off details from `local`. The following config could support both:

```yaml
local:
  default:
    style: docker-compose
    container: web
```

Or should it be more explicit?

```yaml
local:
  default:
    style: docker-compose
    container: web

connect:
  default:
    local: default
```
